[project]
name = "typ2svg"
version = "0.1.0"
description = "pipeline for compiling typst to text-based svgs"
readme = "README.md"
authors = [
    { name = "rctsang", email = "ryan.ying.tsang@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fonttools[woff]>=4.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"
